---
title: "C28125 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28125"
helpviewer_keywords: 
  - "C28125"
ms.assetid: 3f7b8db4-6a64-4480-919e-3f3ceca7f948
caps.latest.revision: 4
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 4
---
# C28125
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

warning C28125: The function must be called from within a try\/except block  
  
 드라이버가 try\/except 블록 내에서 호출해야 하는 함수\(예: [ProbeForRead](http://msdn.microsoft.com/library/windows/hardware/ff559876.aspx), [ProbeForWrite](http://msdn.microsoft.com/library/windows/hardware/ff559879.aspx), [MmProbeAndLockPages](http://msdn.microsoft.com/library/windows/hardware/ff554664.aspx)\)를 호출하고 있습니다.  
  
## 예제  
 다음 코드 예제에서는 이 경고를 생성합니다.  
  
```  
ProbeForRead(addr, len, 4);  
```  
  
 다음 코드 예제에서는 이 경고를 방지합니다.  
  
```  
  
__try  
{  
    ProbeForRead(addr, len, 4);  
}  
__except(EXCEPTION_EXECUTE_HANDLER)  
{  
    Status = GetExceptionCode();  
    ... report error status  
}  
```